spring:
  application:
    name: notification-service
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
management.endpoints.web.exposure.include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${SERVER_PORT:9005}
